### ISSUE TITLE
Frontend Meeting Notes (15/12/2016)

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#105]
# Actions
 - [x] create frontend project board
 - [x] "Your Dashboard" as a fake organisation #106 (@ramitos)
 - [x] go through wireframes to identify the global state #107 (@ramitos)
 - [x] split wireframes into workable units #119
 - [x] do a full inventory of UI components #112 (@alex)
 - [x] do a full inventory of sizes, colours, fonts and assets  #112 (@alex)
 - [ ] uniform the way we use the grid system #110 (@alex)
 - [x] go through the RBAC v2 RFD and identify all entities and make sure we follow naming according to it #111 (@ramitos)
 - [x] example of a UI component (e.g. Tabs) tested with enzyme #113 (@ramitos)
 - [x] example of a state component (with redux) tested #114 (@ramitos)
