### ISSUE TITLE
Ui workable units

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#119]
- [x] service instances (#133)
- [x] service metrics (#134) (@juditgreskovits)
- [x] add metric monitor (@ramitos) (#155)
- [ ] add service metrics  (@juditgreskovits) (#135)
- [x] project people  (#136)
- [x] Tooltip
- [x] Header (https://github.com/yldio/joyent-portal/issues/118)
- [x] Project (#120)
- [x] Services (#121)
- [x] Empty states (services, projects)
- [x] org people
- [x] invite org people
- [x] invite project people (#137)

-------

 - [ ] create new project (#130)
 - [ ] services topology (#132)
 - [ ] project manifest (#131)
