### ISSUE TITLE
Frontend Meeting Notes (04/01/2017)

### ISSUE THREAD

**Issue by ramitos** [yldio/joyent-portal#138]
# From last meeting
 - [x] split wireframes into workable units #119
 - [x] do a full inventory of UI components #112 (@alex)
 - [ ] uniform the way we use the grid system #110 (@alex)

# Actions
 - [ ] continue working through the splitted up workable units (all)
 - [x] spike react form solutions (redux-form, etc) #139 (@juditgreskovits)
 - [ ] continue working on workable units (all) (#119)
 - [x] spike option and select libraries #140 (@alex)
 - [x] redux dev-tools plugin #141 (@juditgreskovits)
 - [x] publish chartjs whiskers plugin #142 (@tomgco ?)
 - [ ] Spacing action items #144
