### ISSUE TITLE
QA notes from Tom

### ISSUE THREAD

**Issue by hollowtf** [yldio/joyent-portal#1392]
General

- [x] Card titles (like 'Instance type and image') should be in semibold, not regular
- [x] 'Collapse' links should read "Save and Collapse"
- [x] Arrow on the left of collapse should be the same colour as the word link, also should be a couple of pixels higher
- [x] 'Optional' tag on cards should be #979797
- [x] Divider line between title of the card and the contents is too wide, should be 30px from left and right hand side of card
- [x] Body copy should only run across the first 8 columns of the grid, not the full width of the container. Please fix this across the CI flow
- [x] Can we change the 'Save' CTA in all cards to read 'Next' instead
- [x] The card that is currently active should have a soft drop shadow behind it. This shadow should only appear when the card is active and should disappear when the card is collapse. The value of the drop shadow can be seen below:
![Screen Shot 2018-05-01 at 12.03.27.png](https://images.zenhubusercontent.com/5a01ddc68a75884b9086663b/5bc0d6e2-430d-43ff-b224-6cc57465917d)

- [ ] Currently, the cards are attached to the grid, however it should be that all the contents are attched to the grid, with the cards spilling over slightly as shown below.
![Screen Shot 2018-05-01 at 12.05.51.png](https://images.zenhubusercontent.com/5a01ddc68a75884b9086663b/303f7732-4dc0-4d19-9c10-b03b3418ce04)

Name this instance

- [x] Should be opened when user first arrives on the page
- [x] Text in the 'randomise' button isn't centred vertically
- [x] Spacing between instance name input and copy is currently 30px, should be 18px

Instance type and Image

- [x] The image type tabs should have an underline of #494949 below the selected option 
- [x] Should be 30px from the top of the text on the image type tabs to the copy above. Currently there is 12px top padding on that component that should be removed.
- [x] There should be only 6px padding between the underline and the text on the image type tabs
- [x] When an image is selected, the icon and text inside that card should all turn #3B46CC
- [x] In the collapsed state, there should be 12px between the image title (the H2) and the image type (the p)

Select package

- [x] The filters div has 6px top margin, please remove this
- [x] Should be 18px horizontal margin between the filter options

Attach to networks

- [x] Unselected cards should have a background of #fafafa behind the title and checkbox (this then changes to be blue when selected)
- [x] Can we loose the drop shadow on the individual network cards please

Tags

- [x] Can we add the number of tags that have been added, inline with the designs
- [x] The cross on tags should be #d8d8d8
- [x] Should be 30px margin between the bottom of a tag and the top of the 'Add a tag' title
- [x] Should be 18px between the tag inputs and the create button 
- [x] Please show number of tags on collapsed state

Metadata
- [x] Can we add the number of metadata key–value pairs added please
- [x] Should be 18px margin between metadata key input and metatdata value input
- [x] No need for drop shadow on the "add metadata' card
- [x] When clicking 'Save' button, the card simply collapses and doesn't open the next card (users scripts). Please fix
- [x] Drop shadow to be removed from the collapsed metadata cards

User scripts

- [ ] When this card is first opened, can the code block show 5 emtpty lines instead of just the 1?

Firewalls

- [x] Can the empty state of firewalls please be aligned with designs (remove the salamander, add cta to show inactive rules, and change copy)
- [x] there is not CTA to 'Save' on this card, oplease add so users can move onto the next step
- [x] Even when firewall is enabled, the copy reads 'Firewall not enabled' in collapsed state

CNS

- [x] When a CNS servic e name is added, the tag should have a background of #3B46CC at 10% opacity

Affinity

- [x] When this card is initially opened, it should automatically should the affinity rule UI, no need to have the 'Create affinity rule' CTA
- [ ] When a value is selected from the drop-downs, its colour should change to #494949 to imply selection 
- [ ] Can width of dropdowns please scale in  regards to what contents is showing in it, currently the component is either too large or too small depending on what is written

**Comment by johnytiago** [comment]
Tags
>  Can we add the number of tags that have been added, inline with the designs
>  Please show number of tags on collapsed state

In the designs, there is no count. Should I mimic the metadata count?
