### ISSUE TITLE
Frontend Meeting Notes (27/01/2017)

### ISSUE THREAD

**Issue by alex-windett** [yldio/joyent-portal#195]
### Rolled Over
- [ ] re-evaluate `unitcalc` @juditgreskovits 
- [ ] Show baseline grid - chrome plugin not enough / significant @alex-windett
- [ ] uniform the way we use the grid system **_continual work_** 

### Actions
- [ ] Continue and improve on making UI / Frontend more consistent with designs @yldio/joyent-technical 
- [ ] Evaluate how far away we are from a technical prototype matching the marvel prototypes
- [ ] Namespace colors and make consistent. There are currently duplicates with similar names that can be deleted @yldio/joyent-technical 
- [ ] Add tests for frontend components and containers - react, redux, application state @yldio/joyent-technical 
- [ ] Continue UI workable units https://github.com/yldio/joyent-portal/issues/119
- [ ] Adding in real data from Prometheus HTTP API https://github.com/yldio/joyent-portal/issues/187
- [ ] Webpack font loader refinement https://github.com/yldio/joyent-portal/issues/160
- [ ] Mini style guide including all colors, fonts, font-sizes etc (low-priority) @yldio/joyent

**Comment by alex-windett** [comment]
Duplicated here so it can live on project board #196
