### ISSUE TITLE
Adding in real data from Prometheus HTTP API [#208]

### ISSUE THREAD

**Issue by juditgreskovits** [yldio/joyent-portal#322]
#208 

Other references:
#187
#83 

Streams:
   1. Wp
      - [ ] deploy WP example #352 
      - [ ] setup artillery with 1day worth of traffic #353 
      - [ ] save prometheus data #354 
 2. Leak
      - [x] boot leak spike example #355 
      - [x] reduce data for charts #356 
      - [ ] play data back in frontend #357 
      - [ ] combine metric and mini-metric into a single component #301
